name: Deploy www.masonlaneous.com

on:
  push:
    paths:
      # only re-build if the "main" app actually changed
      - apps/main/**
      # or if its workflow (this file) changed
      - .github/workflows/main.yaml
      # or package.json changes
      - package.json

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          
      # Build Docker image locally
      - name: Build Docker image
        run: pnpm run build-main
          
      # Deploy the container using docker compose
      - name: Deploy
        run: docker compose -f /home/runner/docker/docker-compose.yml up -d